config/routes.rb
Rails.application.routes.draw do
  #API namespace for JSON requests at /api/sign_[in|out|]
  namespace :api do
    devise_for :users, defaults: { format: :json },
                                class_name: 'ApiUser',
                                skip: [:registrations, :invitations, :passwords, :confirmations, :unlocks],
                                path: '',
                                controllers: {
                                  sessions: 'api/sessions',
                                },
                                path_names: { sign_in: 'login',
                                              sign_out: 'logout' }
    put "events/:id/reservation", :to => "events#reserve_event"
    delete "events/:id/reservation", :to => "events#cancel_event"
    get "events", :to => "events#events"
    get "event_types", :to => "events#event_types"
  end

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  match "*all" => "application#route_options", :constraints => { :method => "OPTIONS" }, :via => "get"


  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
  get "/static/:page" => "pages#show"
  get "schedule" => "pages#schedule", :as => "schedule"
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'refinery/pages#home', :ad => "home_root"
  devise_for :users
    resources :users
  #match '/contacts', to: 'refinery/pages#create', via: 'post'
  resources "contacts", only: [:new, :create]
  match "events/:id/reserve_event", :to => "events#reserve_event", :as => "reserve_event", :via => "post"
  match "events/:id/cancel_event", :to => "events#cancel_event", :as => "cancel_event", :via => "post"
  match "users/:id/renew_membership", :to => "users#renew_membership", :as => "renew_membership", :via => "get"
  match "users/:id/update_membership", :to => "users#update_membership", :as => "update_membership", :via => "post"
  match "users/:id/update_subscribed_event_types", :to => "users#update_subscribed_event_types", :as => "update_subscribed_event_types", :via => "patch"
  match "impersonate/:id" => 'users#impersonate', :via => :get, :as => :impersonate
  match "unimpersonate_user" => 'users#unimpersonate_user', :via => :get, :as => :unimpersonate_user
  match "users/create_user", :to => "users#create_user", :as => "create_user", :via => "post"


  match "users/:id/destroy", :to => "users#destroy", :as => "delete_user", :via => "post"

  match "users/:id/approve", :to => "users#approve", :as => "approve_user", :via => "get"
  match "schedule_data", :to => "events#data", :as => "data", :via => "get"
  match "db_action", :to => "events#db_action", :as => "db_action", :via => "post"

end

app/controllers/refinery/admin/core_controller.rb
module Refinery
  module Admin
    class CoreController < ::Refinery::AdminController
      def index
        redirect_to refinery_admin_root_path
      end
    end
  end
end

app/controllers/refinery/admin/dialogs_controller.rb
module ::Refinery
  module Admin
    class DialogsController < ::Refinery::AdminController
      TYPES = %w[image link]

      before_action :find_dialog_type, :find_iframe_src, :only => [:show]

      def index
        redirect_to Refinery::Core.backend_path
      end

      def show
        render :layout => false
      end

      def from_dialog?
        true
      end

      protected

      def find_dialog_type
        error_404 if TYPES.exclude? params[:id].downcase

        @dialog_type = params[:id].downcase
      end

      def find_iframe_src
        if @dialog_type == 'image'
          @iframe_src = refinery.insert_admin_images_path(
            url_params.merge(:modal => true)
          )
        elsif @dialog_type == 'link'
          @iframe_src = refinery.link_to_admin_pages_dialogs_path url_params
        end
      end

      def url_params
        params.reject { |key, value| /(action)|(controller)/ === key}.
               merge :id => nil
      end

    end
  end
end

app/controllers/refinery/admin/images_controller.rb
module Refinery
  module Admin
    class ImagesController < ::Refinery::AdminController

      crudify :'refinery/image',
              include: [:translations],
              order: "updated_at DESC",
              sortable: false

      before_action :change_list_mode_if_specified, :init_dialog

      def new
        @image = ::Refinery::Image.new if @image.nil?

        @url_override = refinery.admin_images_path(dialog: from_dialog?)
      end

      # This renders the image insert dialog
      def insert
        self.new if @image.nil?

        @url_override = refinery.admin_images_path(request.query_parameters.merge(insert: true))

        if params[:conditions].present?
          extra_condition = params[:conditions].split(',')

          extra_condition[1] = true if extra_condition[1] == "true"
          extra_condition[1] = false if extra_condition[1] == "false"
          extra_condition[1] = nil if extra_condition[1] == "nil"
        end

        find_all_images(({extra_condition[0] => extra_condition[1]} if extra_condition.present?))
        search_all_images if searching?

        paginate_images

        render 'insert'
      end

      def create
        @images = []
        begin
          if params[:image].present? && params[:image][:image].is_a?(Array)
            params[:image][:image].each do |image|
              params[:image][:image_title] = params[:image][:image_title].presence || auto_title(image.original_filename)
              @images << (@image = ::Refinery::Image.create({image: image}.merge(image_params.except(:image))))
            end
          else
            @images << (@image = ::Refinery::Image.create(image_params))
          end
        rescue NotImplementedError
          logger.warn($!.message)
          @image = ::Refinery::Image.new
        end

        if params[:insert]
          # if all uploaded images are ok redirect page back to dialog, else show current page with error
          if @images.all?(&:valid?)
            @image_id = @image.id if @image.persisted?
            @image = nil
          end

          self.insert
        else
          if @images.all?(&:valid?)
            flash.notice = t('created', scope: 'refinery.crudify', what: "'#{@images.map(&:image_title).join("', '")}'")
            if from_dialog?
              @dialog_successful = true
              render '/refinery/admin/dialog_success', layout: true
            else
              redirect_to refinery.admin_images_path
            end
          else
            self.new # important for dialogs
            render 'new'
          end
        end
      end

      def update
        @image.attributes = image_params
        if @image.valid? && @image.save
          flash.notice = t('refinery.crudify.updated', what: "'#{@image.title}'")

          if from_dialog?
            self.index
            @dialog_successful = true
            render :index
          else
            if params[:continue_editing] =~ /true|on|1/
              if request.xhr?
                render partial: '/refinery/message'
              else
                redirect_to :back
              end
            else
              redirect_back_or_default refinery.admin_images_path
            end
          end
        else
          @thumbnail = Image.find params[:id]
          if request.xhr?
            render partial: '/refinery/admin/error_messages', locals: {
                     object: @image,
                     include_object_name: true
                   }
          else
            render 'edit'
          end
        end
      end

      protected

      def init_dialog
        @app_dialog = params[:app_dialog].present?
        @field = params[:field]
        @update_image = params[:update_image]
        @thumbnail = params[:thumbnail]
        @callback = params[:callback]
        @multiple = params[:multiple]
        @conditions = params[:conditions]
      end

      def change_list_mode_if_specified
        if action_name == 'index' && params[:view].present? && Refinery::Images.image_views.include?(params[:view].to_sym)
           Refinery::Images.preferred_image_view = params[:view]
        end
      end

      def paginate_images
        @images = @images.paginate(page: params[:page], per_page: Image.per_page(from_dialog?, !@app_dialog))
      end

      def restrict_controller
        super unless action_name == 'insert'
      end

      def auto_title(filename)
        CGI::unescape(filename.to_s).gsub(/\.\w+$/, '').titleize
      end

      def image_params
        params.require(:image).permit(permitted_image_params)
      end

      private

      def permitted_image_params
        [
          { image: [] }, :image_size, :image_title, :image_alt
        ]
      end

    end
  end
end

app/controllers/refinery/admin/page_parts_controller.rb
module Refinery
  module Admin
    class PagePartsController < ::Refinery::AdminController

      def new
        render :partial => '/refinery/admin/pages/page_part_field', :locals => {
                 :part => ::Refinery::PagePart.new(new_page_part_params),
                 :new_part => true,
                 :part_index => params[:part_index]
               }
      end

      def destroy
        part = ::Refinery::PagePart.find(params[:id])
        page = part.page
        if part.destroy
          page.reposition_parts!
          render :text => "'#{part.title}' deleted."
        else
          render :text => "'#{part.title}' not deleted."
        end
      end

      protected
        def new_page_part_params
          params.except(:part_index).permit(:title, :slug, :body, :locale)
        end

    end
  end
end

app/controllers/refinery/admin/pages_controller.rb
module Refinery
  module Admin
    class PagesController < Refinery::AdminController
      prepend Pages::InstanceMethods

      crudify :'refinery/page',
              :include => [:translations, :children],
              :paging => false

      helper_method :valid_layout_templates, :valid_view_templates

      def new
        @page = Page.new(new_page_params)
        Pages.default_parts_for(@page).each_with_index do |page_part, index|
          @page.parts << PagePart.new(:title => page_part[:title], :slug => page_part[:slug], :position => index)
        end
      end

      def children
        @page = find_page
        render :layout => false
      end

      def update
        if @page.update_attributes(page_params)
          flash.notice = t('refinery.crudify.updated', what: "'#{@page.title}'")

          if from_dialog?
            self.index
            @dialog_successful = true
            render :index
          else
            if params[:continue_editing] =~ /true|on|1/
              if request.xhr?
                render partial: 'save_and_continue_callback',
                       locals: save_and_continue_locals(@page)
              else
                redirect_to :back
              end
            else
              redirect_back_or_default(refinery.admin_pages_path)
            end
          end
        else
          if request.xhr?
            render :partial => '/refinery/admin/error_messages', :locals => {
              :object => @page,
              :include_object_name => true
            }
          else
            render 'edit'
          end
        end
      end

      protected

      def after_update_positions
        find_all_pages
        render :partial => '/refinery/admin/pages/sortable_list' and return
      end

      def find_page
        @page = Page.find_by_path_or_id!(params[:path], params[:id])
      end
      alias_method :page, :find_page

      # We can safely assume ::Refinery::I18n is defined because this method only gets
      # Invoked when the before_action from the plugin is run.
      def globalize!
        return super unless action_name.to_s == 'index'

        # Always display the tree of pages from the default frontend locale.
        if Refinery::I18n.built_in_locales.keys.map(&:to_s).include?(params[:switch_locale])
          Globalize.locale = params[:switch_locale].try(:to_sym)
        else
          Globalize.locale = Refinery::I18n.default_frontend_locale
        end
      end

      def valid_layout_templates
        Pages.layout_template_whitelist & Pages.valid_templates(*Pages.layout_templates_pattern)
      end

      def valid_view_templates
        Pages.valid_templates(*Pages.view_templates_pattern)
      end

      def page_params
        params.require(:page).permit(permitted_page_params)
      end

      def new_page_params
        params.permit(:parent_id, :view_template, :layout_template)
      end

      private

      def permitted_page_params
        [
          :browser_title, :draft, :link_url, :menu_title, :meta_description,
          :parent_id, :skip_to_first_child, :show_in_menu, :title, :view_template,
          :layout_template, :custom_slug, parts_attributes: [:id, :title, :slug, :body, :position]
        ]
      end

      def save_and_continue_locals(page)
        nested_url = page.nested_url
        {
          new_refinery_edit_page_path: refinery.admin_edit_page_path(nested_url),
          new_refinery_page_path: refinery.admin_page_path(nested_url),
          new_page_path: refinery.pages_admin_preview_page_path(nested_url)
        }
      end
    end
  end
end

app/controllers/refinery/admin/pages_dialogs_controller.rb
module Refinery
  module Admin
    class PagesDialogsController < ::Refinery::Admin::DialogsController

      helper :'refinery/admin/pages'

      def link_to
        # Get the switch_local variable to determine the locale we're currently editing
        # Set up Globalize with our current locale
        Globalize.locale = if params[:switch_locale].present? && Refinery::I18n.built_in_locales.keys.map(&:to_s).include?(params[:switch_locale])
          Globalize.locale = params[:switch_locale]
        else
          Refinery::I18n.default_locale
        end

        @pages = ::Refinery::Page.roots.paginate(:page => params[:page], :per_page => ::Refinery::Page.per_page(true))

        @pages = @pages.with_globalize

        if ::Refinery::Plugins.registered.names.include?('refinery_files')
          @resources = Resource.paginate(:page => params[:resource_page], :per_page => Resource.per_page(true)).
                                order('created_at DESC')

          # resource link
          if params[:current_link].present?
            is_resource_link = params[:current_link].include?("/system/resources")
          end
        end

        # web address link
        @web_address_text = "http://"
        @web_address_text = params[:current_link] if params[:current_link].to_s =~ /^http:\/\//
        @web_address_target_blank = (params[:target_blank] == "true")

        # mailto link
        if params[:current_link].present?
          if params[:current_link] =~ /^mailto:/
            @email_address_text = params[:current_link].split("mailto:")[1].split('?')[0]
          end
          @email_default_subject_text = params[:current_link].split('?subject=')[1] || params[:subject]
          @email_default_body_text = params[:current_link].split('?body=')[1] || params[:body]
        end

        if params[:paginating].present?
          @page_area_selected = (params[:paginating] == "your_page")
          @resource_area_selected = (params[:paginating] == "resource_file")
        else
          @page_area_selected = (!is_resource_link and @web_address_text == "http://" and @email_address_text.blank?)
          @web_address_area_selected = (@web_address_text != "http://")
          @email_address_area_selected = @email_address_text.present?
          @resource_area_selected = is_resource_link
        end
      end

    end
  end
end

app/controllers/refinery/admin_controller.rb
# Filters added to this controller apply to all controllers in the refinery backend.
# Likewise, all the methods added will be available for all controllers in the refinery backend.
module Refinery
  class AdminController < ::ActionController::Base
    include ::Refinery::ApplicationController
    helper Refinery::Core::Engine.helpers
    include Refinery::Admin::BaseController
    # before_action :authenticate_user!

    # def current_refinery_user
    #   current_user
    # end

  end
end

app/controllers/refinery/fast_controller.rb
module Refinery
  class FastController < ActionController::Base

    def message
      render :partial => '/refinery/message', :layout => false
    end

  end
end

app/controllers/refinery/sitemap_controller.rb
module ::Refinery
  class SitemapController < ::Refinery::FastController
    layout nil

    def index
      headers['Content-Type'] = 'application/xml'

      respond_to do |format|
        format.xml do
          @locales = Refinery::I18n.frontend_locales
        end
      end
    end

  end
end

app/views/refinery/admin/_continue_editing.html.erb
<%= f.submit t('.save_and_continue_editing'),
             :id => "submit_continue_button",
             :class => "wymupdate button" if f.object.persisted? %>

app/views/refinery/admin/_dialog_success.html.erb
<head>
  <script>parent.refinery_dialog_success();</script>
</head>
<body>
</body>

app/views/refinery/admin/_error_messages.html.erb
<% if object.errors.any? %>
<div class="errorExplanation error_icon" id="errorExplanation">
  <p><%= t('.problems_in_following_fields') %>:</p>
  <ul>
  <% if defined?(include_object_name) and include_object_name %>
    <% object.errors.full_messages.each do |value| %>
      <li><%= value %></li>
    <% end %>
  <% else %>
    <% object.errors.each do |key, value| %>
      <li><%= value %></li>
    <% end %>
  <% end %>
  </ul>
</div>
<% end %>

app/views/refinery/admin/_form_actions.html.erb
<%
  unless (hide_submit ||= false)
    submit_button_text  ||= t('.save')
    submit_button_id    ||= "submit_button"
    submit_button_title ||= nil
  end

  hide_cancel = from_dialog? unless defined?(hide_cancel).presence

  unless hide_cancel
    cancel_button_text  ||= t('.cancel')
    unless defined?(cancel_title)
      cancel_title = t('.cancel_lose_changes')
    end
    cancel_button_id    ||= "cancel_button"
    cancel_url          ||= (((back = url_for(:back)).include?('javascript') or action_name =~ /^(create|update)$/) ? refinery.send(Refinery.route_for_model(f.object.class, :plural => true)) : back)
  end

  continue_editing = defined?(continue_editing) ? continue_editing : (f.object.present? and f.object.persisted?)

  unless defined?(hide_delete).presence
    hide_delete = (from_dialog? or
                   f.object.nil? or (f.object.respond_to?(:persisted?) ? !f.object.persisted? : f.object.new_record?) or
                   (f.object.respond_to?(:deletable?) && !f.object.deletable?))
  end

  unless hide_delete
    delete_button_text  ||= t('.delete')
    delete_title        ||= nil
    delete_confirmation ||= nil
    delete_button_id    ||= "delete_button"
    # we have to use eval rather than refinery.send because this url may not exist for HTTP GET
    delete_url          ||= eval("refinery.#{Refinery.route_for_model(f.object.class)}(#{f.object.id})")
  end
-%>
<% if from_dialog? %>
<input type='hidden' name='modal' value='true' />
<input type='hidden' name='dialog' value='true' />
<% end %>

<div class='form-actions<%= ' form-actions-dialog' if from_dialog? %>'>
  <div class='form-actions-left'>
    <%= submit_tag submit_button_text,
                   :id => submit_button_id,
                   :name => nil,
                   :class => "wymupdate button",
                   :tooltip => submit_button_title unless hide_submit %>

    <%= render '/refinery/admin/continue_editing', :f => f if continue_editing -%>
    <%= hidden_field_tag :continue_editing, false if continue_editing %>

    <%= local_assigns[:before_cancel_button] -%>

    <%= link_to(cancel_button_text, cancel_url,
                :title => cancel_title,
                :id => cancel_button_id,
                :class => "close_dialog button") unless hide_cancel %>

    <%= local_assigns[:after_cancel_button] -%>
    <i id='spinner' class='loading_icon hidden_icon'></i>
  </div>
  <div class='form-actions-right'>
    <%= local_assigns[:before_delete_button] -%>
    <%= link_to(delete_button_text, delete_url,
                :title => delete_title,
                :id => delete_button_id,
                :method => :delete,
                :data => {
                  :confirm => delete_confirmation
                },
                :class => "button confirm-delete") unless hide_delete %>
    <%= local_assigns[:after_delete_button] -%>
  </div>
</div>

app/views/refinery/admin/_form_advanced_options_menu.html.erb
<div id="more_options_field" >
  <p>
    <%= action_label(:settings, '#', t('.toggle_advanced_options'), id: 'toggle_advanced_options') %>

  <span id="draft_field">
    <%= f.check_box :draft %>
    <%= f.label :draft, t('.save_as_draft'),
                :class => 'stripped' %>
  </span>
   </p>
</div>

app/views/refinery/admin/_head.html.erb
<head>
  <meta charset='<%= ::Rails.application.config.encoding %>' />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <%= yield :meta %>
  <title><%= Refinery::Core.site_name -%> - Refinery</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'refinery/refinery' %>
  <% visual_editor_stylesheets.each do |css| %>
    <%= stylesheet_link_tag css.path, css.options %>
  <% end %>
  <% custom_stylesheets.each do |css| %>
    <%= stylesheet_link_tag css.path, css.options %>
  <% end %>
  <%= yield :stylesheets %>
  <%= render 'refinery/admin/javascripts' %>
</head>

app/views/refinery/admin/_image_picker.html.erb
<%
  description ||= 'image'
  thumbnail ||= 'medium'
  toggle_image_display ||= false
  conditions ||= nil
  randomiser = rand(Time.now.yesterday.to_i * Time.now.to_i)
  current_image_link_href = refinery.insert_admin_images_path(:dialog => true, :callback => "image_picker_#{randomiser}_changed",
                                                    :width => 866, :height => 510, :conditions => conditions)
  current_image_title = t('.change', :what =>  description.titleize)
-%>
<div id='image_picker_container_<%= randomiser %>'>
  <%= link_to t('.show'), '', :class => "current_image_toggler" if toggle_image_display %>
  <%= f.hidden_field field, :class => "current_image_id" -%>

  <div class='current_image_container' style="margin-top: 10px<%= ";display: none" if toggle_image_display %>">
    <a class='current_image_link dialog' href="<%= current_image_link_href %>" style='border: 0px' title='<%= current_image_title  %>' name='<%= current_image_title %>'>
      <% if image.nil? -%>
        <img class="current_picked_image" src="" alt="" style='display: none' />
      <% else -%>
        <%= image_fu image, Refinery::Images.user_image_sizes[thumbnail.to_sym],
                     :class => "brown_border current_picked_image" %>
      <% end -%>
      <span class='no_picked_image_selected nothing_selected'<%= " style='display: none;'".html_safe if image.present? %>>
        <%= t('.none_selected') %>
      </span>
    </a>
    <br/>
    <%= link_to t('.remove_current'), "#",
                :class => "remove_picked_image",
                :style => "#{"display:none;" if image.nil?}" %>
  </div>
</div>

<% content_for :javascripts do -%>
  <script>
    var image_picker_<%= randomiser %> = {};
    $(document).ready(function(e) {
      $.extend(true, image_picker_<%= randomiser %>, image_picker)
      image_picker_<%= randomiser %> = image_picker_<%= randomiser %>.init({
        thumbnail: '<%= thumbnail.html_safe %>'
        , image_toggler: '<%= toggle_image_display ? ".current_image_toggler" : "null" %>'
        , description: '<%= description %>'
        , field: '.current_image_id'
        , image_display: '.current_picked_image'
        , no_image_message: '.no_picked_image_selected'
        , remove_image_button: '.remove_picked_image'
        , picker_container: '#image_picker_container_<%= (lambda {randomiser}).call %>'
        , image_container: '.current_image_container'
        , image_link: '.current_image_link'
      });
    });

    image_picker_<%= randomiser %>_changed = function(args){
      $.proxy(image_picker_<%= randomiser %>.changed, {
        container: '#image_picker_container_<%= randomiser %>'
        , picker: image_picker_<%= randomiser %>
        , image: args
      })();
    };
  </script>
<% end %>

app/views/refinery/admin/_locale_picker.html.erb
<input type="hidden" name="switch_locale" id="switch_locale" value="<%= local_assigns[:current_locale] %>" />
<% if Refinery::I18n.frontend_locales.many? %>
  <label><%= t('.language') %></label>
  <ul id="switch_locale_picker" class="clearfix">
    <% locales = Refinery::I18n.locales.clone %>
    <% Refinery::I18n.frontend_locales.each do |locale| %>
      <% locale_name = locales.delete(locale) %>
      <li<%= %Q{ class=selected} if locale.to_s == local_assigns[:current_locale].to_s %>>
        <%= link_to refinery.url_for(:switch_locale => locale, :parent_id => params[:parent_id]), id: locale do %>
          <div class="<%=locale %> locale_marker">
            <%= locale_text_icon(locale.upcase) %>
          </div>
          <%= locale_name %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/refinery/admin/_make_sortable.html.erb
<% content_for :after_javascript_libraries do %>
  <%= javascript_include_tag 'refinery/sortable_list' %>
  <%= javascript_include_tag 'refinery/nestedsortables' %>
  <%= javascript_include_tag 'refinery/serializelist' %>
  <%= javascript_include_tag 'refinery/tree' %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      create_sortable_list(
        <%= raw({
              update_url: refinery.url_for(action: "update_positions", only_path: true),
              sortable_list: '#sortable_list, .sortable_list',
              tree: false,
              replaceContentsAfterUpdate: false
            }.merge(options ||= {}).to_json) %>
      );
    });
  </script>
<% end %>

app/views/refinery/admin/_menu_item.html.erb
<%= link_to menu_item.title, refinery.url_for(menu_item.url),
            :class => ("active" if menu_item.highlighted?(params)),
            :id => "plugin_#{menu_item.name}" %>

app/views/refinery/admin/_resource_picker.html.erb
<%
  insert_link = refinery.insert_admin_resources_path({
                  :dialog => true,
                  :update_resource => "current_resource_#{field}",
                  :update_text => "current_resource_text_#{field}",
                  :callback => "resource_changed_#{field}",
                  :field => [f.object_name.gsub(/\]\[|[^-a-zA-Z0-9:.]/, '_').sub(/_$/, ''), field].join('_'),
                  :current_link => "#{resource.url if resource}",
                  :height => 480,
                  :conditions => local_assigns[:conditions]
                })
 %>
<%= f.hidden_field field %>

<div>
  <%= action_icon :add, insert_link, t('.name'), id: "current_resource_link_#{field}" unless resource %>

  <div id="current_resource_container_<%= field %>" style="margin-top: 10px;<%= ' display: none;' unless resource %>">
    <span class="current_resource" id="<%="current_resource_text_#{field}"%>">
      <%= "#{resource.title} (#{resource.file_name})" if resource %>
    </span>
    <div id='resource_actions'>
      <%= action_icon :download, "#{resource.url if resource}", t('.download_current'), id: "current_resource_#{field}" %>
      <%= action_icon :remove, '#', t('.remove_current'), :id => "remove_resource_#{field}"%>
    </div>
  </div>
</div>

<% content_for :javascripts do %>
  <script>
    resource_changed_<%= field %> = function(callback_args) {
      $('#remove_resource_<%= field %>').show();
      $('#current_resource_container_<%= field %>').show();
      $('#no_resource_selected_<%= field %>').hide();
      $('iframe#dialog_iframe').dialog('close');
      $('iframe#dialog_iframe').remove().parents('.ui-dialog').remove();
      $('#<%= f.object_name.gsub(/\]\[|[^-a-zA-Z0-9:.]/, '_').sub(/_$/, '') %>_<%= field %>').val(callback_args.id);
      $('#current_resource_link_<%= field %>').attr('href', $('#current_resource_link_<%= field %>').attr('href').replace(/current_link=([^&])*&/, 'current_link=' + callback_args.href + '&'));
      $('#current_resource_<%= field %>').attr('href', callback_args.href);
      $('#current_resource_text_<%= field %>').html(callback_args.html);
    };

    $(document).ready(function(e) {
      $('#remove_resource_<%= field %>').click(function(e) {
        $('#<%= f.object_name %>_<%= field %>').val('');
        $('#current_resource_container_<%= field %>').hide();
        $('#current_resource_text_<%= field %>').html('');
        $('#no_resource_selected_<%= field %>').show();
        $('#current_resource_link_<%= field %>').attr('href', $('#current_resource_link_<%= field %>').attr('href').replace(/current_link=([^&])*&/, 'current_link=&'));
        $(this).hide();
        e.preventDefault();
      });
    });
  </script>
<% end %>

app/views/refinery/admin/_search.html.erb
<%= render 'refinery/acts_as_indexed/admin/search', local_assigns if defined?(Refinery::ActsAsIndexed::Engine) -%>

app/views/refinery/admin/_sortable_list.html.erb
<% if params[list_id ||= "sortable_list"].present? and !!local_assigns[:continue_reordering] -%>
  <script>
    $(document).ready(function(){
      list_reorder.enable_reordering();
    });
  </script>
<% end -%>

app/views/refinery/admin/_wysiwyg.html.erb
<div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
  <ul id='page_parts'>
    <% fields.each_with_index do |part, part_index| %>
      <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
        <%= link_to t("#{part}", :scope => "activerecord.attributes.refinery/#{object}", :default => part.to_s.titleize), "##{part}" %>
      </li>
    <% end %>
  </ul>
  <div id='page_part_editors'>
    <% fields.each do |part| %>
      <div class='page_part' id='<%= part %>'>
        <%= f.text_area part, :rows => 20, :class => 'visual_editor widest' -%>
      </div>
    <% end %>
  </div>
</div>