config/routes.rb
Rails.application.routes.draw do
  #API namespace for JSON requests at /api/sign_[in|out|]
  namespace :api do
    devise_for :users, defaults: { format: :json },
                                class_name: 'ApiUser',
                                skip: [:registrations, :invitations, :passwords, :confirmations, :unlocks],
                                path: '',
                                controllers: {
                                  sessions: 'api/sessions',
                                },
                                path_names: { sign_in: 'login',
                                              sign_out: 'logout' }
    put "events/:id/reservation", :to => "events#reserve_event"
    delete "events/:id/reservation", :to => "events#cancel_event"
    get "events", :to => "events#events"
    get "event_types", :to => "events#event_types"
  end

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  match "*all" => "application#route_options", :constraints => { :method => "OPTIONS" }, :via => "get"


  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
  get "/static/:page" => "pages#show"
  get "schedule" => "pages#schedule", :as => "schedule"
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'refinery/pages#home', :ad => "home_root"
  devise_for :users
    resources :users
  #match '/contacts', to: 'refinery/pages#create', via: 'post'
  resources "contacts", only: [:new, :create]
  match "events/:id/reserve_event", :to => "events#reserve_event", :as => "reserve_event", :via => "post"
  match "events/:id/cancel_event", :to => "events#cancel_event", :as => "cancel_event", :via => "post"
  match "users/:id/renew_membership", :to => "users#renew_membership", :as => "renew_membership", :via => "get"
  match "users/:id/update_membership", :to => "users#update_membership", :as => "update_membership", :via => "post"
  match "users/:id/update_subscribed_event_types", :to => "users#update_subscribed_event_types", :as => "update_subscribed_event_types", :via => "patch"
  match "impersonate/:id" => 'users#impersonate', :via => :get, :as => :impersonate
  match "unimpersonate_user" => 'users#unimpersonate_user', :via => :get, :as => :unimpersonate_user
  match "users/create_user", :to => "users#create_user", :as => "create_user", :via => "post"


  match "users/:id/destroy", :to => "users#destroy", :as => "delete_user", :via => "post"

  match "users/:id/approve", :to => "users#approve", :as => "approve_user", :via => "get"
  match "schedule_data", :to => "events#data", :as => "data", :via => "get"
  match "db_action", :to => "events#db_action", :as => "db_action", :via => "post"

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin, :coach]
  enum status: [:active, :pending, :expired, :deactivated]
  validates :email, :presence => true, length: { maximum: 50 }
  validates :email, :email => true, :uniqueness => true
  validates :name, :presence => true, length: { maximum: 50 } #, too_long: "First and last name are too long. Maximum combined length is 50 characters." }
  validates :password, :presence => true, :length => { :in => 6..120 }, :if => :password_required?
  validates_confirmation_of :password, :if => :password_required?

  has_many :plugins,-> { order 'position ASC'}, :class_name => "Refinery::UserPlugin"
  accepts_nested_attributes_for :plugins
  after_initialize :set_default_role, :if => :new_record?
  after_create :send_admin_mail
  has_and_belongs_to_many :events
  scope :ready, -> { where(status:[0,2]) }
  def password_required?
   !persisted? || !password.blank? || !password_confirmation.blank?
  end

  def set_default_role
    self.role ||= :user
  end

  def events_to_hash_per_day(from, to)
    week_events = events.where(start_date:from.to_datetime.beginning_of_day..to.to_datetime.beginning_of_day)
    Hash[*week_events.map{|ue| [ue.start_date.strftime("%Y-%m-%d"), ue.event_type]}.flatten]
  end

  def events_to_hash_per_hour(from, to)
    week_events = events.where(start_date:from.to_datetime.beginning_of_day..to.to_datetime.beginning_of_day)
    Hash[*week_events.map{|ue| [ue.start_date.strftime("%Y-%m-%d %H:%M"), ue.event_type]}.flatten]
  end

  def reserved_for?(date, event_type)
    events.where(start_date:date.beginning_of_day..date.end_of_day, event_type:Event.event_types[event_type]).size > 0
  end

  def authorized_plugins
    plugins.collect { |p| p.name } | ::Refinery::Plugins.always_allowed.names
  end

  def has_plugin?(name)
    active_plugins.names.include?(name)
  end

  def active_plugins
    @active_plugins ||= Refinery::Plugins.new(
      Refinery::Plugins.registered.select do |plugin|
        admin? || authorised_plugins.include?(plugin.name)
      end
    )
  end

  def plugins=(plugin_names)
    if persisted? # don't add plugins when the user_id is nil.
      ::Refinery::UserPlugin.delete_all(:user_id => id)

      plugin_names.each_with_index do |plugin_name, index|
        plugins.create(:name => plugin_name, :position => index) if plugin_name.is_a?(String)
      end
    end
  end

  def maintainer?
    admin? || coach?
  end

  def has_role?(title)
    # raise ::ArgumentError, "Role should be the title of the role not a role object." if title.is_a?(::Refinery::Authentication::Devise::Role)
    admin?
  end


  def authorized_plugins
    plugins.collect(&:name) | ::Refinery::Plugins.always_allowed.names
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  def active_for_authentication?
    super && (active? || expired?)
  end

  def username
    name
  end

  def self.send_group_email
    @users = User.all
    total = @users.size
    count = 0
    @users.each do |user|
      count = count + 1
      CustomerMailer.new_web_site_email(user).deliver
      if (count % 50) == 0
        sleep(30)
      end
    end
  end

  def send_admin_mail
    self.update(membership_updated_at: Time.current)
    CustomerMailer.signup_confirmation_email(self).deliver
  end

  def landing_url
    active_plugins.in_menu.first_url_in_menu
  end

  def can_delete?(user_to_delete = self)
    user_to_delete.persisted? &&
      !user_to_delete.admin? &&
      User.admin.any? &&
      id != user_to_delete.id
  end

  def can_edit?(user_to_edit = self)
    user_to_edit.persisted? && (user_to_edit == self || self.admin?)
  end

  def inactive_message
    if pending?
      :not_approved
    elsif deactivated?
      :membership_expired
    else
      super # Use whatever other message
    end
  end

  def self.roles_mapping
    { "Član" => :user, "Administrator" => :admin , "Trener" => :coach }
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :maintainer_only, except: [:unimpersonate_user]
  respond_to :html, :json, only:[:new, :edit, :update, :create_user]

  def index
    prepare_meta_tags title: "Članovi", description: "Ažuriranje članova"
   
    @user = User.new
    respond_to do |format|
      format.html
      format.json{ render json: UsersDatatable.new(view_context)}
    end
  end

  def new
    @user = User.new
    respond_modal_with @user
  end

  def edit
    @user = User.find(params[:id])
    respond_modal_with @user
  end

  def create_user
    @user = User.create(secure_params)
    flash[:notice] = 'Novi član je uspešno dodat.'
    respond_modal_with @user, location: users_path
  end

  def show
    @user = User.find(params[:id])
    unless current_user.maintainer?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def approve
    @user = User.find(params[:id])
    if @user.active!
      CustomerMailer.account_approved_email(@user).deliver
      render json:{success:true, message:t("user_approved")}
    else
      render json:{error:@user.errors.full_messages}
    end
  end

  def update_membership
    @user = User.find(params[:id])
    if @user.update_attributes(membership_updated_at: params[:user][:membership_updated_at].to_date.in_time_zone)
      if @user.membership_updated_at <= (Time.current - 35.days)
        @user.expired!
      else
        @user.active!
      end
      render json:{success:true, message:t("user_membership_updated")}
    else
      render json:{error:@user.errors.full_messages}
    end
  end

  def renew_membership
    @user = User.find(params[:id])
    if @user.update_attributes(membership_updated_at: @user.membership_updated_at + 30.days)
      @user.active!
      CustomerMailer.account_approved_email(@user).deliver
      render json:{success:true, message:t("user_membership_renewed")}
    else
      render json:{error:@user.errors.full_messages}
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(secure_params)
    flash[:notice] = 'Član je uspešno ažuriran.'
    respond_modal_with @user, location: users_path
    #   render json:{success:true, message:t("user_role_updated")}
    # else
    #   render json:{error:@user.errors.full_messages}
    # end 
  end

  def update_subscribed_event_types
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
       render json:{success:true, message:t("user_role_updated")}
    else
       render json:{error:@user.errors.full_messages}
    end 
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    render json:{success:true, message:t("user_deleted")}
  end

  def unimpersonate_user
    if !session[:stack_admins].blank?
      new_user = User.find(session[:stack_admins].last)
      sign_in(new_user, bypass: true)
      session[:stack_admins].pop
    end
    redirect_to users_path

  end

  def impersonate
    from_user_id = current_user.id
    to_user_id = params[:id]
    session[:stack_admins] = Array.new if session[:stack_admins].blank?
    session[:stack_admins] << from_user_id
    to_user = User.find(to_user_id)
    sign_in(to_user, bypass: true)

    redirect_to schedule_path
  end

  private

  def maintainer_only
    unless current_user.maintainer?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role, :password, :password_confirmation, :name, :email, :membership_updated_at, :subscribed_event_types => [])
  end

end

app/views/users/_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= simple_form_for(@user, url:url, remote: request.xhr?, html: { data: { modal: true } }) do |f|%>

<!--   <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 -->

  <%# Added Bootstrap classes, and help-block container for error messages %>
  <%= f.input :name, class: 'form-control' %>
  <%= f.input :email, class: 'form-control' %>


  <% if !@user.persisted? %>
    <div class="row">
      <div class="col-xs-6">   
        <%= f.input :password, class: 'form-control' %>
      </div>
      <div class="col-xs-6">   
        <%= f.input :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  <%end%>

  <div class="form-group">
    <%= f.label :membership_updated_at, class: 'control-label' %><br>
    <div class="input-group date">
    <%= f.text_field :membership_updated_at, :value =>(@user.persisted? ? @user.membership_updated_at.try(:strftime,'%d/%m/%Y') : Time.current.strftime('%d/%m/%Y')),class: 'form-control' %>
       <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
    <span class="help-block"></span>
  </div>
  <% if !@user.persisted? %>
    <input type="hidden" name ="user[status]" value="active">
  <% end %>
  <%# Added Bootstrap classes, and help-block container for error messages %>
  <div class="form-group">
    <%= f.input :role, collection: User.roles_mapping, selected: @user.role || User.roles[:user], disabled: !current_user.admin? || current_user.id == @user.id  %>
    <span class="help-block"></span>
  </div>
 
  <div class="form-group">
    <%= f.label :subscribed_event_types, class: 'control-label'%><br>
    <% left,right = Event.event_types.keys.in_groups(2, false)%>
    <div class="row">
      <div class="col-xs-6">   
       <% left.each_with_index do |type, index| %>
           <label class='control-label'>

           <input id='<%="user_subscribed_event_types_#{index}"%>' name="user[subscribed_event_types][]" class="BSswitch training" type="checkbox" value="<%=type%>" data-off-text="Ne" data-on-text="Da" <%=@user.subscribed_event_types.try(:include?,type) || @user.admin? || !@user.persisted? ? "checked" : "" %> <%=@user.admin? ? " readonly" : ""%>><%="
                              #{type.titleize}"%></label><br><br>
        <% end %>
      </div>
      <div class="col-xs-6">    
       <% right.each_with_index do |type, index| %>
           <label class='control-label'>
           <input id='<%="user_subscribed_event_types_#{index}"%>' name="user[subscribed_event_types][]" class="BSswitch training" type="checkbox" data-off-text="Ne" value="<%=type%>" data-on-text="Da" <%=@user.subscribed_event_types.try(:include?,type) || @user.admin?  || !@user.persisted? ? "checked" : "" %> <%=@user.admin? ? " readonly" : ""%>>
                              <%="#{type.titleize}"%></label><br><br>
        <% end %>
      </div>
    </div>
    <span class="help-block"></span>
  </div>


<% end %>

app/views/users/_links.html.erb
<div class="btn-group">
<!--   <button type="button" class="btn btn-danger" <%= user.admin? ? 'disabled' :''%>><%=t 'users.action'%></button> -->
  <div role="button" data-toggle="dropdown">
  <%=image_tag asset_path("imgs/setting.png")%>
   <!--  <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span> -->
  </div>
  <ul class="dropdown-menu" role="menu">
   <li><%= link_to(t('users.approve'), "javascript:;", :data => { user_id: user.id}, class:"approve") if user.pending? %></li>
   <li><%= link_to 'Ažuriraj', edit_user_path(user), 
            data: { modal: true } %></li>
   <li><%= link_to "Impersoniraj", impersonate_path(user) if (user.active? || user.expired?) && user != current_user %></li>
   <li><%= link_to(t('users.renew'), "javascript:;", :data=>{user_id:user.id}, class:"renew") if (user.expired? || user.deactivated?) %></li>
   <li><%= link_to(t('users.delete'), "javascript:;", :data => { :user_id => user.id }, class:"delete") unless user == current_user %></li>
  </ul>
</div>

app/views/users/_membership.html.erb
<div class="form-group">
  <div class='input-group date'>

      <input type='text' data-user-id="<%=user.id%>" <%=(user.admin? || user.pending?) ? "disabled": ""%> value="<%=user.membership_updated_at.try(:strftime,'%d/%m/%Y')%>" class="form-control" style="width: 150px" />
      <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
      </span>
  </div>
</div>

app/views/users/_user.html.erb
  <%= simple_form_for(user, url:update_subscribed_event_types_path(user)) do |f| %>
    <% if user.admin? %>
      <%= f.select(:subscribed_event_types, 
     Event.event_types.keys.map {|event| "<option value='#{event}' selected >#{event.titleize}</option>"}.join().html_safe, {}, html_options = {class:'checkbox', multiple:"multiple", disabled:true, style:"display:none"}) %>
    <% else %>
    <%= f.select(:subscribed_event_types, 
    Event.event_types.keys.map {|event| "<option value='#{event}' #{user.subscribed_event_types.to_s.include?(event) ? 'selected' : ''}>#{event.titleize}</option>"}.join().html_safe, {}, html_options = {class:'checkbox', multiple:"multiple", style:"display:none"}) %>
    <% end %>
  <% end %> 

app/views/users/edit.html.erb
<% content_for :title, 'Ažuriraj'%>
<%= render :partial => 'form', :locals => { :url => user_path(@user)}%>

app/views/users/index.html.erb
<%= hidden_field_tag 'model_name', 'users' %>
<div class="container">
  <div class="box">

  <div class="col-lg-12">
      <hr>
      <h2 class="intro-text text-center">
          <strong><%=t 'users.title'%></strong>
      </h2>
      <hr>
  </div>
  <div class="col-lg-12">
    <div id="alerts" data-alerts="alerts" data-titles="{'warning': '<em>Warning!</em>'}" data-ids="myid" data-fade="3000"></div>
  </div>
<div class="filter-container" style="display:none">
   <label><%=t 'users.show'%>: 
   <%=select_tag("users-filter", options_for_select([[t("users.filters.all_users"), "all"]] + User.statuses.keys.collect {|status| [t("users.filters.#{status}"),status]} + [["Administratore", "admin"], ["Trenere", "coach"], ["Članove", "user"]]), html_options = {style:"display:none", class:"filter"})%>
  </label>
  <%= link_to t('create_user'), new_user_path, data: { modal: true }, class:"btn btn-primary" %>
</div>


<div class="table-responsive" style="position: relative; overflow: visible;">
<table class="admin-table table display responsive no-wrap" data-source="<%= users_path(format: :json) %>" style="display:none">
      <thead>
        <tr>
          <th data-priority="1"><%=t 'users.name_header'%><div class="img-sorting"></div></th>
          <th data-priority="3"><%=t 'users.training_header'%><div class="img-sorting"></div></th>
          <th data-priority="4"><%=t 'users.status_header'%><div class="img-sorting"></div></th>
          <th data-priority="5"><%=t 'users.membership_updated_at_header'%><div class="img-sorting"></div></th>
          <th data-priority="6"><%=t 'users.created_at_header'%><div class="img-sorting"></div></th>
          <th data-priority="2"><%=t 'users.actions_header', :default => t("helpers.actions") %><div class="img-sorting"></div></th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
    <div id="table-loading" style="display: none">
        <div id="loading-background" class="loading-overlay"><%= image_tag "table-loader.gif", :class => "loader spin center" %></div>
    </div>
  </div>
  </div>
<%# Added Bootstrap data modal attribute %>


</div>


<% content_for :extra_js do %>
   <script>
   
 
    var tableOptions = createTableOptions(); 
    tableOptions.sDom = "<'admin-page-header clear'<'manage_user-id left'><'right'f>r>t<'row table-footer'<'col-md-4'l><'col-md-3' <'text-center'i>><'col-md-5'p>>",
    
    tableOptions.bStateSave = true;
    // tableOptions.aoColumnDefs = [
    //         { responsivePriority: 1},
    //         { responsivePriority: 3},
    //         { responsivePriority: 4},
    //         { responsivePriority: 5},
    //         { responsivePriority: 2}
    //     ]
     // tableOptions.aoColumns = [  
     //    { "sClass":"middle"},
     //    { "sClass":"middle"},
     //    { "sClass":"middle"},
     //    { "sClass":"middle"},
     //    { "sClass":"middle"},
     //    { "sClass":"middle"} ];
    //Send filter as param to server
    tableOptions.oLanguage =

    {
        sProcessing:   "Procesiranje u toku...",
        sLengthMenu:   "Prikaži _MENU_ elemenata",
        sZeroRecords:  "Nije pronađen nijedan rezultat",
        sInfo:         "Prikaz _START_ do _END_ od ukupno _TOTAL_ elemenata",
        sInfoEmpty:    "Prikaz 0 do 0 od ukupno 0 elemenata",
        sInfoFiltered: "(filtrirano od ukupno _MAX_ elemenata)",
        sInfoPostFix:  "",
        sSearchPlaceholder:"Pretraga:",
        sSearch:       "Pretraga:",
        sUrl:          "",
        oPaginate: {
            sFirst:    "Početna",
            sPrevious: "Prethodna",
            sNext:     "Sledeća",
            sLast:     "Poslednja"
        }
    }
    tableOptions.fnServerParams = function (aoData) {
      oControls = $('.filter-container').find('.filter');
      oControls.each(function() {
        if ( $(this).attr('id') ){
            var filter_text = $(this).val().replace('"', '"').trim();
            aoData[$(this).attr('id')] =  filter_text.indexOf("all") == 0 ? "" : $(this).val().replace('"', '"').trim();
        }
      });
    };
    tableOptions.fnStateSaveParams = function ( oSettings, sValue ) {
      oControls = $('.filter-container').find('.filter');
      oControls.each(function() {
          if ($(this).attr('id')){
            sValue[ $(this).attr('id') ] = $(this).val().replace('"', '"').trim();
            
          }
      });
      return sValue;
    };
    //Restore applied custom filter values when page reloads
    tableOptions.fnStateLoadParams = function ( oSettings, oData ) {
      oControls = $('.filter-container').find('.filter');
      //Load custom filters
      oControls.each(function() {
        var oControl = $(this);
        //    alert(oControl.get(0).tagName);
        $.each(oData, function(index, value) {
          if ( index == oControl.attr('id')){
              oControl.val( value );
          }
        });
      });
      return true;
    }

    



    var filter_container = $('.filter-container');
    createDataTable(tableOptions);
    
    $('.manage_user-id').append(filter_container);
    filter_container.show();
  

   $(document).off("click", "#new_person_modal .btn-default");

    $(document).on("click", "#new_person_modal .btn-default", function (e) {
         $('#new_person_modal form').submit();
      });

      $(document).on('shown.bs.modal', function (e) {
      $('#new_person_modal select.checkbox').multiselect({ numberDisplayed: 3, buttonWidth: '100%', multiple: true, nonSelectedText: 'Nije izabran nijedan',
            nSelectedText: 'izabrana',
            allSelectedText: 'Svi treninzi'
        });
        $('.BSswitch').bootstrapSwitch({size:"small"});
        $('.BSswitch.role').on('switchChange.bootstrapSwitch', function(event, state) {
          if (state === true) {
            $('.BSswitch.training').bootstrapSwitch('state', true);
            $('.BSswitch.training').bootstrapSwitch('readonly', true);
          } else {
            $('.BSswitch.training').bootstrapSwitch('readonly', false);
          }
        });

        $('#new_person_modal select.role').multiselect({
          buttonWidth: '100%',
        }); 

        $('#new_person_modal .input-group.date').datetimepicker({
          locale: 'rs',
          format: 'DD/MM/YYYY'
        });
    });
    $("#alerts").bsAlerts({'titles': {'success': ''}, 'fade':"3000"});
      $(document).trigger("add-alerts", [
      <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
            {
              'message': "<%=msg%>",
              'priority': "<%=name.to_s == 'notice' ? 'success' : 'danger'%>"
            },
      <% end %>
    <% end %>
          ]);

    $('.table').on( 'draw.dt', function () {
        $('.input-group.date').datetimepicker({
          locale: 'rs',
          format: 'DD/MM/YYYY'
        });
        $('.approve').click(function(){
          approve_user($(this).attr('data-user-id'));
        });
        $('.delete').click(function(){
          getConfirm('Da li ste sigurni da želite da obrišete korisnika?', function(data){
            if (data === true) {
             delete_user($(this).attr('data-user-id'));
            }
          }.bind(this));
        });

        $('.renew').click(function(){
          renew_user($(this).attr('data-user-id'));
        });

        $('.input-group.date').on("dp.change", function (e) {
          getConfirm('Da li st sigurni da želite da izvršite promenu?', function(data){
            if (data === true) {
             update_membership(e.date, $(this).find("input").attr("data-user-id"));
            }
          }.bind(this));
        });
        $("[rel=tooltip]").tooltip({ placement: 'top'});
          $('select.checkbox').multiselect({buttonWidth:280, numberDisplayed: 3, multiple: true, onChange: function(element, checked) {
            var form = $(element).closest("form");
            update_user(form);
          }, nonSelectedText: 'Nije izabran nijedan',
            nSelectedText: 'izabrana',
            allSelectedText: 'Svi treninzi'
        });
        $('select#users-filter').multiselect({ onChange: function(element, checked) {
          $('.admin-table').DataTable().draw();
            // $('.table').DataTable().columns(2).search($(element).val().toLowerCase()).draw();
          }
        });
        $('.m-wrap.medium').addClass("form-control");
        $('select.breathe').multiselect();
        $('select.role').multiselect( { buttonWidth:60, onChange: function(element, checked) {
            var form = $(element).closest("form"); 
           update_user(form);
          }
        });
      });



    function delete_user(user_id){
      jQuery.ajax({
        type: "POST",
        dataType: 'json',
        url:  "/users/" + user_id + "/destroy",
        success: function(data) {
          if (!data.error){
          $('.admin-table').DataTable().draw();
           $(document).trigger("add-alerts", [
            {
              'message': data.message,
              'priority': 'success'
            }
          ]);
         }
        }.bind(this),
        error: function(error) {
            alert(error);
        }.bind(this),
        timeout: 30000
      });
    } 

     function approve_user(user_id){
      jQuery.ajax({
        type: "GET",
        dataType: 'json',
        url: '/users/' + user_id + "/approve",
        success: function(data) {
          if (!data.error){
          $('.admin-table').DataTable().draw();
           $(document).trigger("add-alerts", [
            {
              'message': data.message,
              'priority': 'success'
            }
          ]);
         }
        }.bind(this),
        error: function(error) {
            alert(error);
        }.bind(this),
        timeout: 30000
      });
    } 

    function renew_user(user_id){
      jQuery.ajax({
        type: "GET",
        dataType: 'json',
        url:  '/users/' +user_id + "/renew_membership",
        success: function(data) {
          if (!data.error){
          $('.admin-table').DataTable().draw();
           $(document).trigger("add-alerts", [
            {
              'message': data.message,
              'priority': 'success'
            }
          ]);
         }
        }.bind(this),
        error: function(error) {
            alert(error);
        }.bind(this),
        timeout: 30000
      });
    } 

    function update_membership( date, user_id){
      jQuery.ajax({
        type: "POST",
        dataType: 'json',
        data: {user:{membership_updated_at: date.format('YYYY-MM-DD')}},
        url:   '/users/' + user_id + "/update_membership",
        success: function(data) {
          if (!data.error){
          $('.admin-table').DataTable().draw();
           $(document).trigger("add-alerts", [
            {
              'message': data.message,
              'priority': 'success'
            }
          ]);
         }
        }.bind(this),
        error: function(error) {
            alert(error);
        }.bind(this),
        timeout: 30000
      });
    } 


    function update_user(form){
      $(form).find(".loading").show();
      jQuery.ajax({
        type: "POST",
        dataType: 'json',
        data: $(form).serialize(),
        url:  $(form).attr('action'),
        success: function(data) {
          if (!data.error){
          $('.admin-table').DataTable().draw();
           $(document).trigger("add-alerts", [
            {
              'message': data.message,
              'priority': 'success'
            }
          ]);
         }
        }.bind(this),
        error: function(error) {
            alert(error);
        }.bind(this),
        timeout: 30000
      });
    }

  function getConfirm(confirmMessage,callback){
    confirmMessage = confirmMessage || '';

     BootstrapDialog.show({
      type: BootstrapDialog.TYPE_WARNING,
      title: 'Da li ste sigurni?',
      message: confirmMessage,
      buttons: [{
        label: 'Da',
        cssClass: 'btn-primary',
        action: function(dialogRef){
          dialogRef.close();
          if (callback) callback(true);
        }
      }, {
        label: 'Odustani',
        action: function(dialogRef){
          dialogRef.close();
          if (callback) callback(false);
        }
      }]
    });
   };

</script>

<%end%>

app/views/users/new.html.erb
<% content_for :title, 'Novi član'%>
<%= render :partial => 'form', :locals => { :url => create_user_path()}%>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>